version: '3.7'
services:
 automation-playwright:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run docker:run:test
    volumes:
      - ./test-results:/test-results
      - ./allure-report:/allure-report
      - ./allure-results:/allure-results